/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\projects\\Rodx-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0278b6b2",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0278b6b2").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-04ced807",
    path: "/docs/theme-reco/algorithm/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04ced807").then(next)
    },
  },
  {
    name: "v-4c52a098",
    path: "/docs/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c52a098").then(next)
    },
  },
  {
    name: "v-5c779337",
    path: "/docs/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c779337").then(next)
    },
  },
  {
    path: "/docs/theme-reco/index.html",
    redirect: "/docs/theme-reco/"
  },
  {
    name: "v-0d855df2",
    path: "/docs/theme-reco/engineering/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d855df2").then(next)
    },
  },
  {
    name: "v-2fd8792d",
    path: "/docs/theme-reco/html&css/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fd8792d").then(next)
    },
  },
  {
    name: "v-3b5f93d0",
    path: "/docs/theme-reco/html&css/%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA%E7%9C%81%E7%95%A5%E6%95%88%E6%9E%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b5f93d0").then(next)
    },
  },
  {
    path: "/docs/theme-reco/html&css/文本溢出省略效果.html",
    redirect: "/docs/theme-reco/html&css/%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA%E7%9C%81%E7%95%A5%E6%95%88%E6%9E%9C.html"
  },
  {
    path: "/docs/theme-reco/html&css/文本溢出省略效果.html",
    redirect: "/docs/theme-reco/html&css/%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA%E7%9C%81%E7%95%A5%E6%95%88%E6%9E%9C.html"
  },
  {
    name: "v-e2c624b2",
    path: "/docs/theme-reco/html&css/opacity&visibilty&display.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2c624b2").then(next)
    },
  },
  {
    name: "v-1ba34dca",
    path: "/docs/theme-reco/html&css/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ba34dca").then(next)
    },
  },
  {
    path: "/docs/theme-reco/html&css/水平垂直居中.html",
    redirect: "/docs/theme-reco/html&css/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html"
  },
  {
    path: "/docs/theme-reco/html&css/水平垂直居中.html",
    redirect: "/docs/theme-reco/html&css/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html"
  },
  {
    name: "v-6a91a343",
    path: "/docs/theme-reco/js/Functor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a91a343").then(next)
    },
  },
  {
    name: "v-e0bcc79e",
    path: "/docs/theme-reco/js/PointFree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0bcc79e").then(next)
    },
  },
  {
    name: "v-0c9ea933",
    path: "/docs/theme-reco/js/Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c9ea933").then(next)
    },
  },
  {
    name: "v-79d883cf",
    path: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79d883cf").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/函数式编程.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/docs/theme-reco/js/函数式编程.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-1ec80224",
    path: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E6%98%AF%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ec80224").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/函数是一等公民.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E6%98%AF%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91.html"
  },
  {
    path: "/docs/theme-reco/js/函数是一等公民.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E6%98%AF%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91.html"
  },
  {
    name: "v-3a51993d",
    path: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E7%BB%84%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a51993d").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/函数组合.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E7%BB%84%E5%90%88.html"
  },
  {
    path: "/docs/theme-reco/js/函数组合.html",
    redirect: "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E7%BB%84%E5%90%88.html"
  },
  {
    name: "v-521fc709",
    path: "/docs/theme-reco/js/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-521fc709").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/异步编程.html",
    redirect: "/docs/theme-reco/js/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/docs/theme-reco/js/异步编程.html",
    redirect: "/docs/theme-reco/js/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-6a3c10c0",
    path: "/docs/theme-reco/js/%E6%9F%AF%E9%87%8C%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a3c10c0").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/柯里化.html",
    redirect: "/docs/theme-reco/js/%E6%9F%AF%E9%87%8C%E5%8C%96.html"
  },
  {
    path: "/docs/theme-reco/js/柯里化.html",
    redirect: "/docs/theme-reco/js/%E6%9F%AF%E9%87%8C%E5%8C%96.html"
  },
  {
    name: "v-26818a8c",
    path: "/docs/theme-reco/js/%E7%BA%AF%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26818a8c").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/纯函数.html",
    redirect: "/docs/theme-reco/js/%E7%BA%AF%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/docs/theme-reco/js/纯函数.html",
    redirect: "/docs/theme-reco/js/%E7%BA%AF%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-11d9d4b0",
    path: "/docs/theme-reco/js/%E9%97%AD%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11d9d4b0").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/闭包.html",
    redirect: "/docs/theme-reco/js/%E9%97%AD%E5%8C%85.html"
  },
  {
    path: "/docs/theme-reco/js/闭包.html",
    redirect: "/docs/theme-reco/js/%E9%97%AD%E5%8C%85.html"
  },
  {
    name: "v-108cd86a",
    path: "/docs/theme-reco/js/%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-108cd86a").then(next)
    },
  },
  {
    path: "/docs/theme-reco/js/高阶函数.html",
    redirect: "/docs/theme-reco/js/%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/docs/theme-reco/js/高阶函数.html",
    redirect: "/docs/theme-reco/js/%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-d79fd75a",
    path: "/docs/theme-reco/more/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d79fd75a").then(next)
    },
  },
  {
    name: "v-7e0b4d67",
    path: "/docs/theme-reco/network/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e0b4d67").then(next)
    },
  },
  {
    name: "v-06d4aee7",
    path: "/docs/theme-reco/vue/bfc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06d4aee7").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-1368f1aa",
    path: "/tag/tag4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1368f1aa").then(next)
    },
    meta: {"pid":"tags","id":"tag4"}
  },
  {
    path: "/tag/tag4/index.html",
    redirect: "/tag/tag4/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-325af58c",
    path: "/tag/BFC/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-325af58c").then(next)
    },
    meta: {"pid":"tags","id":"BFC"}
  },
  {
    path: "/tag/BFC/index.html",
    redirect: "/tag/BFC/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-5c9b2e55",
    path: "/tag/函数/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5c9b2e55").then(next)
    },
    meta: {"pid":"tags","id":"函数"}
  },
  {
    path: "/tag/函数/index.html",
    redirect: "/tag/函数/"
  },
  {
    name: "v-eec8ec48",
    path: "/tag/闭包/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-eec8ec48").then(next)
    },
    meta: {"pid":"tags","id":"闭包"}
  },
  {
    path: "/tag/闭包/index.html",
    redirect: "/tag/闭包/"
  },
  {
    name: "v-5ce69b59",
    path: "/categories/category2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5ce69b59").then(next)
    },
    meta: {"pid":"categories","id":"category2"}
  },
  {
    path: "/categories/category2/index.html",
    redirect: "/categories/category2/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-61150b86",
    path: "/categories/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-61150b86").then(next)
    },
    meta: {"pid":"categories","id":"HTML"}
  },
  {
    path: "/categories/HTML/index.html",
    redirect: "/categories/HTML/"
  },
  {
    name: "v-35a53628",
    path: "/categories/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-35a53628").then(next)
    },
    meta: {"pid":"categories","id":"JS"}
  },
  {
    path: "/categories/JS/index.html",
    redirect: "/categories/JS/"
  },
  {
    name: "v-7f71ddbe",
    path: "/tag/JS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f71ddbe").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/page/2/index.html",
    redirect: "/tag/JS/page/2/"
  },
  {
    name: "v-12f30dc8",
    path: "/tag/函数/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12f30dc8").then(next)
    },
    meta: {"pid":"tags","id":"函数"}
  },
  {
    path: "/tag/函数/page/2/index.html",
    redirect: "/tag/函数/page/2/"
  },
  {
    name: "v-bd09bad6",
    path: "/categories/JS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd09bad6").then(next)
    },
    meta: {"pid":"categories","id":"JS"}
  },
  {
    path: "/categories/JS/page/2/index.html",
    redirect: "/categories/JS/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]