/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rod",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "关于我",
        "tagline": "冒泡工程师，业余王者老玩家，做饭一般的厨子",
        "bgImage": "/hero1.jpg",
        "bgImageStyle": {
          "height": "520px",
          "color": "#fff"
        },
        "isShowTitleInHome": true,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0278b6b2",
      "path": "/",
      "lastUpdated": "5/23/2022, 1:23:17 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "tags": [
          "tag4"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/docs/theme-reco/algorithm/bfc.html",
      "relativePath": "docs/theme-reco/algorithm/bfc.md",
      "key": "v-04ced807",
      "path": "/docs/theme-reco/algorithm/bfc.html",
      "lastUpdated": "5/22/2022, 8:39:26 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "publish": false
      },
      "regularPath": "/docs/theme-reco/api.html",
      "relativePath": "docs/theme-reco/api.md",
      "key": "v-4c52a098",
      "path": "/docs/theme-reco/api.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "publish": false
      },
      "regularPath": "/docs/theme-reco/",
      "relativePath": "docs/theme-reco/README.md",
      "key": "v-5c779337",
      "path": "/docs/theme-reco/",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "tags": [
          "tag4"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/docs/theme-reco/engineering/bfc.html",
      "relativePath": "docs/theme-reco/engineering/bfc.md",
      "key": "v-0d855df2",
      "path": "/docs/theme-reco/engineering/bfc.html",
      "lastUpdated": "5/22/2022, 8:39:26 PM"
    },
    {
      "title": "BFC 及其应用",
      "frontmatter": {
        "title": "BFC 及其应用",
        "date": "2020-05-18T00:00:00.000Z",
        "tags": [
          "CSS",
          "HTML",
          "BFC"
        ],
        "categories": [
          "CSS",
          "HTML"
        ]
      },
      "regularPath": "/docs/theme-reco/html&css/bfc.html",
      "relativePath": "docs/theme-reco/html&css/bfc.md",
      "key": "v-2fd8792d",
      "path": "/docs/theme-reco/html&css/bfc.html",
      "headers": [
        {
          "level": 2,
          "title": "是什么：",
          "slug": "是什么"
        },
        {
          "level": 2,
          "title": "怎么触发：",
          "slug": "怎么触发"
        },
        {
          "level": 2,
          "title": "特性：",
          "slug": "特性"
        },
        {
          "level": 2,
          "title": "解决了什么",
          "slug": "解决了什么"
        }
      ],
      "lastUpdated": "5/22/2022, 8:39:26 PM"
    },
    {
      "title": "如何用 css 或 js 实现多行文本溢出省略效果，考虑兼容性",
      "frontmatter": {
        "title": "如何用 css 或 js 实现多行文本溢出省略效果，考虑兼容性",
        "date": "2020-05-18T00:00:00.000Z",
        "tags": [
          "CSS",
          "HTML"
        ],
        "categories": [
          "CSS",
          "HTML"
        ]
      },
      "regularPath": "/docs/theme-reco/html&css/%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA%E7%9C%81%E7%95%A5%E6%95%88%E6%9E%9C.html",
      "relativePath": "docs/theme-reco/html&css/文本溢出省略效果.md",
      "key": "v-3b5f93d0",
      "path": "/docs/theme-reco/html&css/%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA%E7%9C%81%E7%95%A5%E6%95%88%E6%9E%9C.html",
      "headers": [
        {
          "level": 2,
          "title": "css实现",
          "slug": "css实现"
        },
        {
          "level": 2,
          "title": "js实现",
          "slug": "js实现"
        },
        {
          "level": 2,
          "title": "Eltable 中 textLimit限制超过长度的文本提示框",
          "slug": "eltable-中-textlimit限制超过长度的文本提示框"
        }
      ]
    },
    {
      "title": "隐藏元素方式的优略",
      "frontmatter": {
        "title": "隐藏元素方式的优略",
        "date": "2020-05-18T00:00:00.000Z",
        "tags": [
          "CSS",
          "HTML"
        ],
        "categories": [
          "CSS",
          "HTML"
        ]
      },
      "regularPath": "/docs/theme-reco/html&css/opacity&visibilty&display.html",
      "relativePath": "docs/theme-reco/html&css/opacity&visibilty&display.md",
      "key": "v-e2c624b2",
      "path": "/docs/theme-reco/html&css/opacity&visibilty&display.html",
      "headers": [
        {
          "level": 2,
          "title": "display：none",
          "slug": "display-none"
        },
        {
          "level": 2,
          "title": "visibility：hidden",
          "slug": "visibility-hidden"
        },
        {
          "level": 2,
          "title": "opacity:0",
          "slug": "opacity-0"
        }
      ]
    },
    {
      "title": "水平垂直居中",
      "frontmatter": {
        "title": "水平垂直居中",
        "date": "2020-05-18T00:00:00.000Z",
        "tags": [
          "CSS",
          "HTML"
        ],
        "categories": [
          "CSS",
          "HTML"
        ]
      },
      "regularPath": "/docs/theme-reco/html&css/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "relativePath": "docs/theme-reco/html&css/水平垂直居中.md",
      "key": "v-1ba34dca",
      "path": "/docs/theme-reco/html&css/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "headers": [
        {
          "level": 2,
          "title": "postion方法",
          "slug": "postion方法"
        },
        {
          "level": 2,
          "title": "flex",
          "slug": "flex"
        },
        {
          "level": 2,
          "title": "position方法配置transform",
          "slug": "position方法配置transform"
        }
      ]
    },
    {
      "title": "Functor",
      "frontmatter": {
        "title": "Functor",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/Functor.html",
      "relativePath": "docs/theme-reco/js/Functor.md",
      "key": "v-6a91a343",
      "path": "/docs/theme-reco/js/Functor.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是Functor",
          "slug": "什么是functor"
        },
        {
          "level": 2,
          "title": "实践总结",
          "slug": "实践总结"
        },
        {
          "level": 2,
          "title": "MayBe函子",
          "slug": "maybe函子"
        },
        {
          "level": 2,
          "title": "Either函子",
          "slug": "either函子"
        },
        {
          "level": 2,
          "title": "IO函子",
          "slug": "io函子"
        },
        {
          "level": 2,
          "title": "Task 异步执行",
          "slug": "task-异步执行"
        },
        {
          "level": 2,
          "title": "Pointed函子",
          "slug": "pointed函子"
        },
        {
          "level": 2,
          "title": "Monad函子",
          "slug": "monad函子"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "PointFree",
      "frontmatter": {
        "title": "PointFree",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/PointFree.html",
      "relativePath": "docs/theme-reco/js/PointFree.md",
      "key": "v-e0bcc79e",
      "path": "/docs/theme-reco/js/PointFree.html",
      "headers": [
        {
          "level": 2,
          "title": "PointFree",
          "slug": "pointfree"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/Promise.html",
      "relativePath": "docs/theme-reco/js/Promise.md",
      "key": "v-0c9ea933",
      "path": "/docs/theme-reco/js/Promise.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise状态",
          "slug": "promise状态"
        },
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "常见误区",
          "slug": "常见误区"
        },
        {
          "level": 2,
          "title": "链式调用",
          "slug": "链式调用"
        },
        {
          "level": 2,
          "title": "异常处理",
          "slug": "异常处理"
        },
        {
          "level": 2,
          "title": "最终处理finally",
          "slug": "最终处理finally"
        },
        {
          "level": 2,
          "title": "静态方法",
          "slug": "静态方法"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "函数式编程",
      "frontmatter": {
        "title": "函数式编程",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html",
      "relativePath": "docs/theme-reco/js/函数式编程.md",
      "key": "v-79d883cf",
      "path": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "什么式函数式编程",
          "slug": "什么式函数式编程"
        },
        {
          "level": 2,
          "title": "面向对象编程的思维方式",
          "slug": "面向对象编程的思维方式"
        },
        {
          "level": 2,
          "title": "函数式编程的思维方式",
          "slug": "函数式编程的思维方式"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "函数是一等公民",
      "frontmatter": {
        "title": "函数是一等公民",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E6%98%AF%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91.html",
      "relativePath": "docs/theme-reco/js/函数是一等公民.md",
      "key": "v-1ec80224",
      "path": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E6%98%AF%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91.html",
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "函数组合",
      "frontmatter": {
        "title": "函数组合",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E7%BB%84%E5%90%88.html",
      "relativePath": "docs/theme-reco/js/函数组合.md",
      "key": "v-3a51993d",
      "path": "/docs/theme-reco/js/%E5%87%BD%E6%95%B0%E7%BB%84%E5%90%88.html",
      "headers": [
        {
          "level": 2,
          "title": "管道",
          "slug": "管道"
        },
        {
          "level": 2,
          "title": "如果组合",
          "slug": "如果组合"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "异步编程",
      "frontmatter": {
        "title": "异步编程",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html",
      "relativePath": "docs/theme-reco/js/异步编程.md",
      "key": "v-521fc709",
      "path": "/docs/theme-reco/js/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "js的进程与线程",
          "slug": "js的进程与线程"
        },
        {
          "level": 2,
          "title": "同步模式&异步模式",
          "slug": "同步模式-异步模式"
        },
        {
          "level": 3,
          "title": "同步模式",
          "slug": "同步模式"
        },
        {
          "level": 3,
          "title": "异步模式",
          "slug": "异步模式"
        },
        {
          "level": 3,
          "title": "任务队列",
          "slug": "任务队列"
        },
        {
          "level": 3,
          "title": "事件循环",
          "slug": "事件循环"
        },
        {
          "level": 3,
          "title": "执行栈",
          "slug": "执行栈"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "柯里化",
      "frontmatter": {
        "title": "柯里化",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E6%9F%AF%E9%87%8C%E5%8C%96.html",
      "relativePath": "docs/theme-reco/js/柯里化.md",
      "key": "v-6a3c10c0",
      "path": "/docs/theme-reco/js/%E6%9F%AF%E9%87%8C%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "ladash中的柯里化函数",
          "slug": "ladash中的柯里化函数"
        },
        {
          "level": 2,
          "title": "实践总结",
          "slug": "实践总结"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "纯函数",
      "frontmatter": {
        "title": "纯函数",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E7%BA%AF%E5%87%BD%E6%95%B0.html",
      "relativePath": "docs/theme-reco/js/纯函数.md",
      "key": "v-26818a8c",
      "path": "/docs/theme-reco/js/%E7%BA%AF%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "纯函数的好处",
          "slug": "纯函数的好处"
        },
        {
          "level": 2,
          "title": "副作用",
          "slug": "副作用"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "闭包",
      "frontmatter": {
        "title": "闭包",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "闭包",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E9%97%AD%E5%8C%85.html",
      "relativePath": "docs/theme-reco/js/闭包.md",
      "key": "v-11d9d4b0",
      "path": "/docs/theme-reco/js/%E9%97%AD%E5%8C%85.html",
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "高阶函数",
      "frontmatter": {
        "title": "高阶函数",
        "date": "2021-05-30T00:00:00.000Z",
        "tags": [
          "JS",
          "函数"
        ],
        "categories": [
          "JS"
        ]
      },
      "regularPath": "/docs/theme-reco/js/%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html",
      "relativePath": "docs/theme-reco/js/高阶函数.md",
      "key": "v-108cd86a",
      "path": "/docs/theme-reco/js/%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是高阶函数",
          "slug": "什么是高阶函数"
        },
        {
          "level": 2,
          "title": "使用高阶函数的亿元",
          "slug": "使用高阶函数的亿元"
        },
        {
          "level": 2,
          "title": "常用的高阶函数",
          "slug": "常用的高阶函数"
        }
      ],
      "lastUpdated": "5/23/2022, 12:37:02 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/more/bfc.html",
      "relativePath": "docs/theme-reco/more/bfc.md",
      "key": "v-d79fd75a",
      "path": "/docs/theme-reco/more/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/network/bfc.html",
      "relativePath": "docs/theme-reco/network/bfc.md",
      "key": "v-7e0b4d67",
      "path": "/docs/theme-reco/network/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/vue/bfc.html",
      "relativePath": "docs/theme-reco/vue/bfc.md",
      "key": "v-06d4aee7",
      "path": "/docs/theme-reco/vue/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag4 Tags"
      },
      "regularPath": "/tag/tag4/",
      "key": "v-1368f1aa",
      "path": "/tag/tag4/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "HTML Tags"
      },
      "regularPath": "/tag/HTML/",
      "key": "v-184d950c",
      "path": "/tag/HTML/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "BFC Tags"
      },
      "regularPath": "/tag/BFC/",
      "key": "v-325af58c",
      "path": "/tag/BFC/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "函数 Tags"
      },
      "regularPath": "/tag/%E5%87%BD%E6%95%B0/",
      "key": "v-5c9b2e55",
      "path": "/tag/函数/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "闭包 Tags"
      },
      "regularPath": "/tag/%E9%97%AD%E5%8C%85/",
      "key": "v-eec8ec48",
      "path": "/tag/闭包/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category2 Categories"
      },
      "regularPath": "/categories/category2/",
      "key": "v-5ce69b59",
      "path": "/categories/category2/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "CSS Categories"
      },
      "regularPath": "/categories/CSS/",
      "key": "v-7efe64ca",
      "path": "/categories/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "HTML Categories"
      },
      "regularPath": "/categories/HTML/",
      "key": "v-61150b86",
      "path": "/categories/HTML/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JS Categories"
      },
      "regularPath": "/categories/JS/",
      "key": "v-35a53628",
      "path": "/categories/JS/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - JS | Tags"
      },
      "regularPath": "/tag/JS/page/2/",
      "key": "v-7f71ddbe",
      "path": "/tag/JS/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - 函数 | Tags"
      },
      "regularPath": "/tag/%E5%87%BD%E6%95%B0/page/2/",
      "key": "v-12f30dc8",
      "path": "/tag/函数/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - JS | Categories"
      },
      "regularPath": "/categories/JS/page/2/",
      "key": "v-bd09bad6",
      "path": "/categories/JS/page/2/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "Notes",
        "icon": "reco-message",
        "link": "/docs/theme-reco/"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/rod-x",
            "icon": "reco-github"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1196687670914888",
            "icon": "reco-juejin"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        {
          "title": "HTML&CSS",
          "collapsable": true,
          "children": [
            {
              "title": "BFC及其应用",
              "path": "/docs/theme-reco/html&css/bfc"
            },
            {
              "title": "文本溢出省略效果",
              "path": "/docs/theme-reco/html&css/文本溢出省略效果"
            },
            {
              "title": "水平垂直居中",
              "path": "/docs/theme-reco/html&css/水平垂直居中"
            },
            {
              "title": "隐藏元素方式的优略",
              "path": "/docs/theme-reco/html&css/opacity&visibilty&display"
            }
          ]
        },
        {
          "title": "JS",
          "collapsable": true,
          "children": [
            {
              "title": "闭包",
              "path": "/docs/theme-reco/js/闭包"
            },
            {
              "title": "纯函数",
              "path": "/docs/theme-reco/js/纯函数"
            },
            {
              "title": "高阶函数",
              "path": "/docs/theme-reco/js/高阶函数"
            },
            {
              "title": "函数式编程",
              "path": "/docs/theme-reco/js/函数式编程"
            },
            {
              "title": "函数是一等公民",
              "path": "/docs/theme-reco/js/函数是一等公民"
            },
            {
              "title": "函数组合",
              "path": "/docs/theme-reco/js/函数组合"
            },
            {
              "title": "柯里化",
              "path": "/docs/theme-reco/js/柯里化"
            },
            {
              "title": "异步编程",
              "path": "/docs/theme-reco/js/异步编程"
            },
            {
              "title": "Functor",
              "path": "/docs/theme-reco/js/Functor"
            },
            {
              "title": "PointFree",
              "path": "/docs/theme-reco/js/PointFree"
            },
            {
              "title": "Promise",
              "path": "/docs/theme-reco/js/Promise"
            }
          ]
        },
        {
          "title": "Vue",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/vue/bfc"
            }
          ]
        },
        {
          "title": "前端工程化",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/engineering/bfc"
            }
          ]
        },
        {
          "title": "网络知识",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/network/bfc"
            }
          ]
        },
        {
          "title": "算法",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/algorithm/bfc"
            }
          ]
        },
        {
          "title": "其他",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/more/bfc"
            }
          ]
        }
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": false,
    "logo": "/logo.jpg",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "Rod",
    "authorAvatar": "/logo.jpg",
    "record": "",
    "startYear": "2019"
  }
}