/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rod",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "关于我",
        "tagline": "冒泡工程师，业余王者老玩家，做饭一般的厨子",
        "bgImage": "/hero1.jpeg",
        "bgImageStyle": {
          "height": "520px",
          "color": "#fff"
        },
        "isShowTitleInHome": true,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-14009baa",
      "path": "/",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "publish": false
      },
      "regularPath": "/docs/theme-reco/",
      "relativePath": "docs/theme-reco/README.md",
      "key": "v-3b7c90bb",
      "path": "/docs/theme-reco/",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "tags": [
          "tag4"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/docs/theme-reco/algorithm/bfc.html",
      "relativePath": "docs/theme-reco/algorithm/bfc.md",
      "key": "v-0d7f5703",
      "path": "/docs/theme-reco/algorithm/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z",
        "publish": false
      },
      "regularPath": "/docs/theme-reco/api.html",
      "relativePath": "docs/theme-reco/api.md",
      "key": "v-58a784b0",
      "path": "/docs/theme-reco/api.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/engineering/bfc.html",
      "relativePath": "docs/theme-reco/engineering/bfc.md",
      "key": "v-275df203",
      "path": "/docs/theme-reco/engineering/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/html&css/bfc.html",
      "relativePath": "docs/theme-reco/html&css/bfc.md",
      "key": "v-27548729",
      "path": "/docs/theme-reco/html&css/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/js/bfc.html",
      "relativePath": "docs/theme-reco/js/bfc.md",
      "key": "v-afe97732",
      "path": "/docs/theme-reco/js/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/more/bfc.html",
      "relativePath": "docs/theme-reco/more/bfc.md",
      "key": "v-77b04362",
      "path": "/docs/theme-reco/more/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/network/bfc.html",
      "relativePath": "docs/theme-reco/network/bfc.md",
      "key": "v-6feaaa63",
      "path": "/docs/theme-reco/network/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "title": "bfc",
      "frontmatter": {
        "title": "bfc",
        "date": "2020-05-30T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/vue/bfc.html",
      "relativePath": "docs/theme-reco/vue/bfc.md",
      "key": "v-54eec7e3",
      "path": "/docs/theme-reco/vue/bfc.html",
      "lastUpdated": "5/22/2022, 7:10:21 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag4 Tags"
      },
      "regularPath": "/tag/tag4/",
      "key": "v-1368f1aa",
      "path": "/tag/tag4/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category2 Categories"
      },
      "regularPath": "/categories/category2/",
      "key": "v-5ce69b59",
      "path": "/categories/category2/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "Notes",
        "icon": "reco-message",
        "link": "/docs/theme-reco/"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/rod-x",
            "icon": "reco-github"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1196687670914888",
            "icon": "reco-juejin"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        {
          "title": "HTML&CSS",
          "collapsable": true,
          "children": [
            {
              "title": "BFC及其应用",
              "path": "/docs/theme-reco/html&css/bfc"
            }
          ]
        },
        {
          "title": "JS",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/js/bfc"
            }
          ]
        },
        {
          "title": "Vue",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/vue/bfc"
            }
          ]
        },
        {
          "title": "前端工程化",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/engineering/bfc"
            }
          ]
        },
        {
          "title": "网络知识",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/network/bfc"
            }
          ]
        },
        {
          "title": "算法",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/algorithm/bfc"
            }
          ]
        },
        {
          "title": "其他",
          "collapsable": true,
          "children": [
            {
              "title": "jsBFC及其应用",
              "path": "/docs/theme-reco/more/bfc"
            }
          ]
        }
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": false,
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "Rod",
    "authorAvatar": "/avatar.png",
    "record": "",
    "startYear": "2019"
  }
}