/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "tag4": {
      "key": "tag4",
      "scope": "tags",
      "path": "/tag/tag4/",
      "pageKeys": [
        "v-0d7f5703"
      ]
    }
  },
  "categories": {
    "category2": {
      "key": "category2",
      "scope": "categories",
      "path": "/categories/category2/",
      "pageKeys": [
        "v-0d7f5703"
      ]
    }
  },
  "timeline": {}
}