/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "tag4": {
      "key": "tag4",
      "scope": "tags",
      "path": "/tag/tag4/",
      "pageKeys": [
        "v-04ced807",
        "v-0d855df2"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-2fd8792d",
        "v-3b5f93d0",
        "v-e2c624b2",
        "v-1ba34dca"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-2fd8792d",
        "v-3b5f93d0",
        "v-e2c624b2",
        "v-1ba34dca"
      ]
    },
    "BFC": {
      "key": "BFC",
      "scope": "tags",
      "path": "/tag/BFC/",
      "pageKeys": [
        "v-2fd8792d"
      ]
    },
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-6a91a343",
        "v-e0bcc79e",
        "v-0c9ea933",
        "v-79d883cf",
        "v-1ec80224",
        "v-3a51993d",
        "v-521fc709",
        "v-6a3c10c0",
        "v-26818a8c",
        "v-11d9d4b0",
        "v-108cd86a"
      ]
    },
    "函数": {
      "key": "函数",
      "scope": "tags",
      "path": "/tag/函数/",
      "pageKeys": [
        "v-6a91a343",
        "v-e0bcc79e",
        "v-0c9ea933",
        "v-79d883cf",
        "v-1ec80224",
        "v-3a51993d",
        "v-521fc709",
        "v-6a3c10c0",
        "v-26818a8c",
        "v-11d9d4b0",
        "v-108cd86a"
      ]
    },
    "闭包": {
      "key": "闭包",
      "scope": "tags",
      "path": "/tag/闭包/",
      "pageKeys": [
        "v-11d9d4b0"
      ]
    }
  },
  "categories": {
    "category2": {
      "key": "category2",
      "scope": "categories",
      "path": "/categories/category2/",
      "pageKeys": [
        "v-04ced807",
        "v-0d855df2"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-2fd8792d",
        "v-3b5f93d0",
        "v-e2c624b2",
        "v-1ba34dca"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "categories",
      "path": "/categories/HTML/",
      "pageKeys": [
        "v-2fd8792d",
        "v-3b5f93d0",
        "v-e2c624b2",
        "v-1ba34dca"
      ]
    },
    "JS": {
      "key": "JS",
      "scope": "categories",
      "path": "/categories/JS/",
      "pageKeys": [
        "v-6a91a343",
        "v-e0bcc79e",
        "v-0c9ea933",
        "v-79d883cf",
        "v-1ec80224",
        "v-3a51993d",
        "v-521fc709",
        "v-6a3c10c0",
        "v-26818a8c",
        "v-11d9d4b0",
        "v-108cd86a"
      ]
    }
  },
  "timeline": {}
}