/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "tag4",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/tag4/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "JS",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/JS/","interval":[0,9]},{"path":"/tag/JS/page/2/","interval":[10,11]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "函数",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/函数/","interval":[0,9]},{"path":"/tag/函数/page/2/","interval":[10,11]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "tag2",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/tag2/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "闭包",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/闭包/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "category2",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/category2/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "JS",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/JS/","interval":[0,9]},{"path":"/categories/JS/page/2/","interval":[10,11]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "category3",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/category3/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]